name: Run InstaStory Meal Alert

on:
  schedule:
    - cron: '50 21 * * *' 
  workflow_dispatch: 

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run main script
        run: python main.py
